name: Docker Image CI/CD

on:
  push:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PROJECT_ID: pype-334421
      IMAGE_NAME: devops/docker_build/coywolf-n8n
      VM_NAME: vm-coywolf
      ZONE: us-central1-a
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: GoogleAuth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
    - name: Build
      uses: RafikFarhad/push-to-gcr-github-action@v4
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: us.gcr.io
        project_id: ${{ env.PROJECT_ID }}
        image_name: ${{ env.IMAGE_NAME }}
        image_tag: ${{ steps.vars.outputs.sha_short }}
        context: .
        dockerfile: ./docker/images/n8n-custom/Dockerfile
    - name: Update Deployment
      run: |
        gcloud compute ssh $VM_NAME --project $PROJECT_ID --zone $ZONE --command "source /home/ubuntu/miniconda3/bin/activate && cd /home/ubuntu/localdev && sudo gcloud auth configure-docker --quiet && conda activate localdev && make update-version appName=n8n appVersion=${{ steps.vars.outputs.sha_short }}"
